version: 2
jobs:
  build:
    docker:
      - image: memfault/circleci-codechecker-runner:latest
    steps:
      - checkout
      - run:
          name: Build Demo
          command: |
            cd ext
            for f in `ls *.7z`; do 7za x "$f"; done
            cd ../demos/STM32/RT-STM32F103-STM3210E_EVAL-FATFS-USB
            make 
      - store_artifacts:
          path: ./demos/STM32/RT-STM32F103-STM3210E_EVAL-FATFS-USB/build/ch.elf

  static-analysis:
    docker:
      - image: memfault/circleci-codechecker-runner:latest
    steps:
      - checkout
      - run:
          name: Run CodeChecker
          command: |
            source /home/circleci/codechecker/venv/bin/activate
            cd ext
            for f in `ls *.7z`; do 7za x "$f"; done
            cd ../demos/STM32/RT-STM32F103-STM3210E_EVAL-FATFS-USB
            CodeChecker check -b "make" --output ./reports --enable sensitive --ctu
      - store_artifacts:
          path: ./demos/STM32/RT-STM32F103-STM3210E_EVAL-FATFS-USB/reports

  unit-test:
    docker:
      - image: memfault/circleci-codechecker-runner:latest
    steps:
      - checkout
      - run:
          name: Intall apt packages
          command: 'sudo apt install libc6-dev-i386'
      - run:
          name: Build Unit Tests
          command: |
              cd test/rt/testbuild
              make
      - run:
          name: Run Unit Tests
          command: |
              ./test/rt/testbuild/build/ch

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - static-analysis
      - unit-test
